"""torneoapp

Revision ID: 64a7012108f0
Revises: 
Create Date: 2026-06-24 16:52:08.346599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a7012108f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Kills', sa.String(), nullable=False),
    sa.Column('deaths', sa.String(), nullable=False),
    sa.Column('assits', sa.String(), nullable=False),
    sa.Column('puntos_obtenidos', sa.String(), nullable=False),
    sa.Column('tiempo_partida', sa.Time(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juegos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('ranking', sa.String(), nullable=False),
    sa.Column('victorias', sa.Integer(), nullable=False),
    sa.Column('derrotas', sa.Integer(), nullable=False),
    sa.Column('estadistica_id', sa.Integer(), nullable=False),
    sa.Column('sancion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estadistica_id'], ['estadisticas.id'], ),
    sa.ForeignKeyConstraint(['sancion_id'], ['sanciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ronda', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('estadistica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estadistica_id'], ['estadisticas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torneo_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('torneo_equipos')
    op.drop_table('sanciones')
    op.drop_table('partidas')
    op.drop_table('jugadores')
    op.drop_table('juegos')
    op.drop_table('estadisticas')
    # ### end Alembic commands ###
