"""Migración inicial corregida

Revision ID: dd8425479521
Revises: 
Create Date: 2026-06-29 03:35:10.702321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8425479521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('videojuegos',
    sa.Column('id_videojuego', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_videojuego')
    )
    op.create_table('equipos',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('codigo_equipo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('id_capitan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_capitan'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_equipo'),
    sa.UniqueConstraint('codigo_equipo')
    )
    op.create_table('jugadores',
    sa.Column('id_jugador', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_jugador')
    )
    op.create_table('rankings',
    sa.Column('id_ranking', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('victorias', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ranking')
    )
    op.create_table('sanciones',
    sa.Column('id_sancion', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('fecha_sancion', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sancion')
    )
    op.create_table('torneos',
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('id_videojuego', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_videojuego'], ['videojuegos.id_videojuego'], ),
    sa.PrimaryKeyConstraint('id_torneo')
    )
    op.create_table('equipo_jugadores',
    sa.Column('id_equipo_jugador', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_union', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('rol_equipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_equipo_jugador')
    )
    op.create_table('partidas',
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('ronda', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('id_torneo', sa.Integer(), nullable=True),
    sa.Column('id_equipo1', sa.Integer(), nullable=True),
    sa.Column('id_equipo2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_equipo1'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_equipo2'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_partida')
    )
    op.create_table('torneo_equipo',
    sa.Column('id_torneo_equipo', sa.Integer(), nullable=False),
    sa.Column('id_torneo', sa.Integer(), nullable=True),
    sa.Column('id_equipo', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_torneo_equipo')
    )
    op.create_table('estadisticas',
    sa.Column('id_estadistica', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_partida', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_partida'], ['partidas.id_partida'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_estadistica')
    )
    op.create_table('resultados',
    sa.Column('id_resultado', sa.Integer(), nullable=False),
    sa.Column('marcador_equipo1', sa.Integer(), nullable=True),
    sa.Column('marcador_equipo2', sa.Integer(), nullable=True),
    sa.Column('ganador', sa.String(length=100), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id_partida', sa.Integer(), nullable=True),
    sa.Column('id_torneo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_partida'], ['partidas.id_partida'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_resultado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    op.drop_table('estadisticas')
    op.drop_table('torneo_equipo')
    op.drop_table('partidas')
    op.drop_table('equipo_jugadores')
    op.drop_table('torneos')
    op.drop_table('sanciones')
    op.drop_table('rankings')
    op.drop_table('jugadores')
    op.drop_table('equipos')
    op.drop_table('videojuegos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
